### ISSUE TITLE
JOSS Review

### ISSUE THREAD

**Issue by amoeba** [cimentadaj/perccalc#2]
Hey @cimentadaj, I've had a chance to sit down with `perccalc` 
 and have checked off what I could on the checklist over on https://github.com/openjournals/joss-reviews/issues/1796.

Overall, I think you've done a really nice job with this package, both code, documentation, and tests. Notably, I was immensely appreciative as a reviewer to see you copy in Reardon's code from his implementation for verification, especially as I wasn't able to get my hands on original appendix.

I left a few things unchecked and you'll see why below. Please take a look and let me know if I can explain anything. 

### General Checks

- License: Does the repository contain a plain-text LICENSE file with the contents of an OSI approved software license?

	No, though what's been done is reasonable for an R package. Please change the text of the `LICENSE` file to contain the text of an [OSI Approved license](https://opensource.org/licenses/alphabetical) per the [Review Criteria](https://joss.readthedocs.io/en/latest/review_criteria.html).

### Documentation

(JOSS states that the README at the root should check these boxes. You check these boxes in other places so these are mostly about moving some info to the README)

- A statement of need: Do the authors clearly state what problems the software is designed to solve and who the target audience is?

  Sort of. I think the initial paragraph could be stronger if it had a sentence explaining _why_ someone would want to use this package. The sentence would be intended for a person who doesn't yet know about the method. The paper does a nice job tackling this so maybe something from that could be borrowed.

- Example usage: Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).

  An example is given but with synthetic data. I think it'd be great to try to find a real-world dataset to run the two functions on if possible. Would the GSSvocab dataset work here? The package includes examples with real data in other places and any one of these would be great candidates and would make the README stronger.

### Paper

Overall the paper reads great and I appreciate the time you put into it, it's excellent.

- The paper includes detail in the Examples section that JOSS guidelines indicate should be removed, see [Guidelines](https://joss.readthedocs.io/en/latest/review_criteria.html):

  > "Note the paper should not include software documentation such as API (Application Programming Interface) functionality, as this should be outlined in the software documentation.". Please remove this section.
- The footer has a malformed citation
- The references section needs some DOIs:
  - The reference to Bassok et al. needs a DOI of https://doi.org/10.1177/2332858416653924
  - The reference of Chmielewski and Reardon needs a DOI of https://doi.org/10.1177/2332858416649593
  - The reference of Erikson et al. needs a DOI of https://doi.org/10.2307/589632
  - The reference of Reardon and Portilla needs its DOI of https://doi.org/10.1177/2332858416657343

### Other

I had some other suggestions which are not specific to parts of the JOSS review and can be considered optional:

- I got a warning on this section of the example in the README:

  > perc_diff(df, categorical, continuous, percentiles = c(90, 10))
  difference          se
  79.61141798  0.08179896
  Warning message:
  `cols` is now required.
  Please use `cols = c(value)`

  Could this warning be avoided?

- This errors out in an odd way and could be a more descriptive errors if you think it'd help users:

> perc_diff(df, foo, bar, percentiles = c(90, 10))
Error in category_summary(data_model, variable_name, continuous_name,  :
  is_ordered_fct is not TRUE

  - Typo in "A vector with the percentile difference and it's associated standard error" in perc_diff. "it's"  should be "its".

- In the README, "Reardon (2011)" could be hyperlinked. It's down at the bottom of the readme but I like links when I'm on websites.
- In Usage section of README, the first code block doesn't list `library(perccalc)`. I get that this is listed above in the Installation section but I think it might be more clear to repeat it in this code block

**Comment by briatte** [comment]
Dear all,

Here's my own review.

As I stated when I accepted the review, I know @cimentadaj's high-quality work on other packages, and this one does not disappoint either: it's a very good package that is very clear about what it does and how to use it.

The docs are also excellent, esp. considering that they also document [borderline cases](https://cimentadaj.github.io/perccalc/articles/perc_warning_example.html) where the package is unable to produce all its results.

~~I'm still checking various aspects of the package, but here are some points already.~~ I'm done with the review, for now. All points below are minor, so conditional accept, with very minor revisions.

## General checks

### License
I have left this item unchecked after reading @amoeba's [comment](#issue-509374037), which points to the fact that the [current LICENSE](https://github.com/cimentadaj/perccalc/blob/master/LICENSE) is nonstandard.

The DESCRIPTION file indicates "MIT + file LICENSE", [as recommended by Wickham](http://r-pkgs.had.co.nz/description.html#license), but I guess the LICENSE file needs to include [the actual license](https://opensource.org/licenses/MIT).

I've submitted a PR: https://github.com/cimentadaj/perccalc/pull/3

## Functionality

### Installation
… went perfectly fine on my end, after a few dependency updates.

Suggestion -- would it be better to use `remotes` instead of `devtools` (which uses `remotes` internally) in the installation code?

Also -- like @amoeba, I favour having installation code in the "Install" section of the README, and then have the "Usage" section start with a `library` call.

## Documentation

### Community guidelines
Question -- is it now standard to have the CONTRIBUTING guide in `.github` instead of in the root of the repo?

## Software paper

I've submitted some PRs to it:
- https://github.com/cimentadaj/perccalc/pull/4 (suggested change in first sentence)
- https://github.com/cimentadaj/perccalc/pull/5 (typos)
- https://github.com/cimentadaj/perccalc/pull/6 (code suggestion)

More borderline-pathological nitpicking below.

1.
The code in the paper won't run on old versions of `tidyr` -- specifically, line 145 (copied below) will fail on e.g. `tidyr` 0.8.3, which is what I had installed before updating it to 1.0.0.

```r
nest(data = c(-year, -CNT))
```

2.
> (values of a continuous variable for the 0, 10th, 20th, ..., 100th percentile of the ordered categorical variable)

… That should be either 0, 10th, …, 99th *or* 1st, 10th, …, 100th -- right?

3.
> Mathematics

… Do you need the capital M in English?

### State of the field

I have not yet checked that box because, unless I missed a paragraph somewhere in the paper, the package does not refer to other packages dedicated to working with categorical variables, e.g. [`qualvar`](https://cran.r-project.org/package=qualvar) (disclosure: the author is a friend of mine).

Perhaps it might be worth mentioning a few such packages? Some of them show up in the [CRAN Task View: Official Statistics & Survey Methodology](https://cran.r-project.org/view=OfficialStatistics) -- where `perccalc` should also be listed IMO.

### References

I see that @amoeba has provided the almost-inevitable "missing DOI links" parts of the reviewing process. Thanks to him, since doing so is rather tedious.

To @majensen and JOSS editor(s) -- This happens on many reviews, right? I remember doing the same as @ameoba on a different review. Any way this could be further automated?

## Other

1.

While replicating the README, I was unable to replicate the warning message reported by @amoeba in [his review](#issue-509374037) ("Other" section).

2.

The package has a startup message:

```
Please cite as: 

Cimentada, Jorge (2019). Estimate Percentiles from an Ordered Categorical Variable R package version 1.0.3.
```

I understand the point of having the message, but am not a big fan of startup messages overall.

**Comment by majensen** [comment]
@briatte sorry just saw your comment re DOI links- I can push your suggestion up the chain; thanks!

**Comment by cimentadaj** [comment]
Thank you both for all of the comments, they've made the package much better. To make it easier for you, I've created a new branch `joss_review` [here](https://github.com/cimentadaj/perccalc/tree/joss_review) where you can find all of the commits that address your comments. I will address each of your comments and refer to the commit that implements it whenever possible.

In response to @amoeba's comments

- [X] License: Does the repository contain a plain-text LICENSE file with the contents of an OSI approved software license? 
Commit: 9cb93a653730ab9b458fe0eaca4235b706204c34

Introduced the correct MIT license file

- [X] A statement of need: Do the authors clearly state what problems the software is designed to solve and who the target audience is?
Commit: 7b547a4cc37f5c70f4be7a6acd3e802e1e05024a

As suggested by @amoeba, I borrow some of the explanations from the paper as they are much better clearer there. This is slightly lengthier but explains in detail what the package does and what type of problem it fixes.

- [X] Example usage: Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
Commit: 0c1b11d2535e3255a35118789203525e1775ded9

I've rewritten the entire example using the GSS data and tackling a real world problem. In the example I try to explain exactly how the package addresses the problem.

- [X] The paper includes detail in the Examples section that JOSS guidelines indicate should be removed, see Guidelines: "Note the paper should not include software documentation such as API (Application Programming Interface) functionality, as this should be outlined in the software documentation.". Please remove this section.
Commit: 9f8e8298653244fead5303c27743651fd1eeb6c3

I'm not completely sure this change fixes **all** API discussion but I removed all references to what each function returns or details about the functionality of the functions in the example section. I'm happy to review this further if you think I'm missing some specifics. 

- [X] The footer has a malformed citation
Commit: 4d09f209f6ec5b00c6e2907a309b69aaaa54a013

So useful of you to look up the DOI and thank you very much for pointing this out.

- [X] I got a warning on this section of the example in the README:
```r
        perc_diff(df, categorical, continuous, percentiles = c(90, 10))
        difference se
        79.61141798 0.08179896
        Warning message:
        cols is now required.
        Please use cols = c(value)
```
Commit: 40ef5691b0cdaad63d6d52736d82cfc5827789f4

You're getting the warning because you installed `perccalc` from CRAN, which still has the `tidyr` dependency. In the Github version I've removed almost all dependencies and this is now fixed. I haven't submitted the package to CRAN because I was waiting for this review to finish, so this message should not occur with `devtools::install_github("cimentadaj/perccalc")`. However, in the commit above I did add a minimum version requirement for `tidyr` in the `Suggests` list of the `DESCRIPTION`.

- [X] This errors out in an odd way and could be a more descriptive errors if you think it'd help users:

```r
    perc_diff(df, foo, bar, percentiles = c(90, 10))
    Error in category_summary(data_model, variable_name, continuous_name, :
    is_ordered_fct is not TRUE
```
Commit: 60208d686b63418436918ae587a345f82659befd

I added a more informative message in the commit.

- [X] Typo in "A vector with the percentile difference and it's associated standard error" in perc_diff. "it's" should be "its".
- [X] In the README, "Reardon (2011)" could be hyperlinked. It's down at the bottom of the readme but I like links when I'm on websites.
- [X] In Usage section of README, the first code block doesn't list library(perccalc). I get that this is listed above in the Installation section but I think it might be more clear to repeat it in this code block

The first two changes have been applied in b78d2b0167bedc72ede095824678235cb049ff95 and the second one in 7b547a4cc37f5c70f4be7a6acd3e802e1e05024a

As outlined in the comments, if there's something that you still think that needs more explanation from my part, I'm happy to tackle this. Thanks for taking the time to review the package.

**Comment by cimentadaj** [comment]
In response to @briatte's comments:

- [X] I have left this item unchecked after reading @amoeba's comment, which points to the fact that the current LICENSE is nonstandard. I've submitted a PR: #3
Commit: 9cb93a653730ab9b458fe0eaca4235b706204c34

I fixed this in 9cb93a653730ab9b458fe0eaca4235b706204c34 before I knew that you had issued a PR. Otherwise I would've accepted yours :+1:.

- [X] Suggestion -- would it be better to use remotes instead of devtools (which uses remotes internally) in the installation code?

Hmm, I think it really doesn't matter for the package itself. None of the `devtools` calls in the package are **executed** (they're all in `Rmd` files and `eval` is set to `FALSE`) so `devtools` is not a dependency of `perccalc`. It would make sense to use `remotes` if I would be adding `devtools` as a dependency but fortunately, that can be avoided by not evaluating any call. Thanks for the suggestion though, I hadn't even though about this dependency problem (I even thought `devtools` **would be** a dependency even if you didn't evaluate any chunks of it). 

- [X] Also -- like @amoeba, I favour having installation code in the "Install" section of the README, and then have the "Usage" section start with a library call.
Commit: 7b547a4cc37f5c70f4be7a6acd3e802e1e05024a

Implemented in the commit above.

- [X] Question -- is it now standard to have the CONTRIBUTING guide in .github instead of in the root of the repo?

I'm have no idea to be honest. I can't even remember how/when I added this CONTRIBUTING file. I don't recall doing this manually so it's probably taken from somewhere like `usethis` or something like that.

- [X] I've submitted some PRs to it:
#4 (suggested change in first sentence)
#5 (typos)
#6 (code suggestion)

Thank you very much for the PRs! I wouldn't have noticed these small things. I've accepted all of them in the `master` branch, although all changes related to this are being done in the branch `joss_review`. I'll make sure there aren't any conflicts once I merge `joss_review` into `master`.

- [X] The code in the paper won't run on old versions of tidyr -- specifically, line 145 (copied below) will fail on e.g. tidyr 0.8.3, which is what I had installed before updating it to 1.0.0.
Commit: 40ef5691b0cdaad63d6d52736d82cfc5827789f4

I've added a minimum `tidyr` version to the `Suggests` field in `DESCRIPTION`. This should only have some effect on the vignettes or README since `tidyr` is now removed as a dependency from `perccalc`.

- [X] (values of a continuous variable for the 0, 10th, 20th, ..., 100th percentile of the ordered categorical variable): … That should be either 0, 10th, …, 99th or 1st, 10th, …, 100th -- right?
- [X] Mathematics: … Do you need the capital M in English?

Commit: 1cf7bca338b1df4294f3f7d6b9f326abc8dbf661

Thank you for spotting them. Both typos are fixed in the commit above.

- [X] I have not yet checked that box because, unless I missed a paragraph somewhere in the paper, the package does not refer to other packages dedicated to working with categorical variables, e.g. qualvar (disclosure: the author is a friend of mine).
Commit: 7fe52520901069d6c4d75aad478d52db998ca8d4

Thanks for bringing this up -- I wasn't aware of `qualvar` and it is very much in the same area as `perccalc`. I've included a paragraph with a general overview of categorical-based methods in the paper.

- [X] The package has a startup message: Please cite as: Cimentada, Jorge (2019). Estimate Percentiles from an Ordered Categorical Variable R package version 1.0.3.

Yeah, this is a bit a tricky to refute. This is just an attempt to remind users that the package has indeed a paper attached to it (when published in `JOSS` this will change) and to prime them to recognize this work as academic work as well. This is clearly a contentious topic and I'm experimenting with it in two of my packages. I would prefer to leave it as is for the mean time.

**Comment by briatte** [comment]
> @briatte sorry just saw your comment re DOI links- I can push your suggestion up the chain; thanks!

Please do :)

**Comment by briatte** [comment]
Re: @cimentadaj's messages -- the replies above make sense to me: I'd like to approve the package at that stage.

**Comment by amoeba** [comment]
Thanks for your detailed response to my review @cimentadaj ! It made it easy to inspect your work and verify the changes (which are all great, btw).

Regarding the edits you made the paper, I think it would be appropriate to remove the entire "Example" section in order to better match JOSS' standard. Please take a look at https://joss.readthedocs.io/en/latest/review_criteria.html#the-joss-paper and see if you think my interpretation of those guidelines is correct. Also, look at the most recently published paper for an example: https://joss.theoj.org/papers/10.21105/joss.01642. What do you think?

**Comment by cimentadaj** [comment]
Thanks for the suggestion @amoeba. I wasn't fully aware that examples were not allowed; in fact, I thought they were encouraged.  Taken from the [review criteria](https://joss.readthedocs.io/en/latest/review_criteria.html#example-usage): The authors should include examples of how to use the software (ideally to solve real-world analysis problems).

But I see where you confusion arises from. I'm not entirely sure whether they mean **written** examples or examples that actually use **code**. However, I'm inclined to think that they're ambiguous on this specific point (as in they allow both **written** or **code** examples) because recent papers also include code examples ([here](https://joss.theoj.org/papers/10.21105/joss.01798), [here](https://joss.theoj.org/papers/10.21105/joss.01857), [here](https://joss.theoj.org/papers/10.21105/joss.01722)).

If they allow both types of examples, then I'd prefer keeping the example section as I think it gives a very specific idea of how to solve a real-world problem with the package. This is not meant to be an exhaustive tutorial; for that, the user can read the vignettes of the package which are slightly more elaborate.

Perhaps @briatte has an opinion on this?

**Comment by briatte** [comment]
> Perhaps @briatte has an opinion on this?

Not sure about what JOSS is really saying either, but personally, I think if there's a possibility of having a worked-out example, "(ideally to solve real-world analysis problems)", as per the review criteria, then we should use it.

**Comment by cimentadaj** [comment]
@amoeba, if you think this might be important then we should get the editor involved to see if he can clarify what we should do.

**Comment by amoeba** [comment]
Hey @cimentadaj, @briatte. I'm okay with whatever JOSS says on this. Though, the phrase "The authors should include examples of how to use the software (ideally to solve real-world analysis problems)" is from the Documentation section, not the Paper section of the guidelines, hence my interpretation.

Feel free to bump this up the chain @cimentadaj.

**Comment by cimentadaj** [comment]
@majensen, we're very close to finishing the review but we're confused as to whether JOSS would be okay with the current example I provide in the paper. The example contains a brief code example of what the package works but we're unsure whether JOSS encourages such examples. Can you clarify this for us? If it's ok, then we're done with the review.

**Comment by majensen** [comment]
Thanks @cimentadaj -- @arfon, @labarba would you please chime in here? I personally have no problem with either location, but my experience is still limited as yet.

**Comment by arfon** [comment]
> Thanks @cimentadaj -- @arfon, @labarba would you please chime in here? I personally have no problem with either location, but my experience is still limited as yet.

As the example is rather long (it seems to take the paper to ~6 pages) I'd recommend removing this and perhaps linking to the examples where the are in the docs?

**Comment by majensen** [comment]
@cimentadaj  - per @arfon 's [comment](https://github.com/cimentadaj/perccalc/issues/2#issuecomment-557629955) and @amoeba 's assessment, can we move the full example to docs and make a brief reference to it in the paper (maybe w/ a linkout)? I would think at that point we're good to go.

**Comment by briatte** [comment]
> @cimentadaj - per @arfon 's [comment](https://github.com/cimentadaj/perccalc/issues/2#issuecomment-557629955) and @amoeba 's assessment, can we move the full example to docs and make a brief reference to it in the paper (maybe w/ a linkout)? I would think at that point we're good to go.

This looks like a good solution to me. I also think we're good to go on this package -- the review process did not find anything that critically needs fixing.

**Comment by cimentadaj** [comment]
I've removed the example section from the paper and indicated that there are a full-featured examples in the package's website. I think we should be good to go after this. @majensen I think we're done here!

**Comment by amoeba** [comment]
@cimentadaj looks good to me. I have no outstanding, unresolved review items left so my review is now an _Accept_. I'll go indicate as much over on https://github.com/openjournals/joss-reviews/issues/1796 too.

**Comment by majensen** [comment]
@cimentadaj would you like to merge joss_review into master?

**Comment by cimentadaj** [comment]
Should be merged now.

-----------------------------------


Jorge Cimentada
*https://cimentadaj.github.io/ <https://cimentadaj.github.io/>*

**Comment by cimentadaj** [comment]
Thanks to all for the review!
